apiVersion: v1
kind: Pod
metadata:
  name: twitchrat-dev
spec:
  containers:
  - name: twitchrat-dev
    command: ["twitchrat/rat.py"]
    args: ["-s", "quin69", "--influxdb-database", "quin69chatdev"]
    env:
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: clientid
          name: twitch-api-access
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: clientsecret
          name: twitch-api-access
    - name: INFLUXDB_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: influxdb-operator-token
    image: registry.digitalocean.com/xf86/twitchrat-dev:latest
    imagePullPolicy: Always

