apiVersion: v1
kind: Pod
metadata:
  name: twitchrat
spec:
  containers:
  - name: twitchrat
    command: ["twitchrat/rat.py"]
    args: ["-s", "quin69", "--influxdb-database", "quin69chat"]
    env:
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: clientid
          name: twitch-api-access
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: clientsecret
          name: twitch-api-access
    - name: INFLUXDB_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: influxdb-operator-token
    image: registry.digitalocean.com/xf86/twitchrat:latest
    imagePullPolicy: Always

